### ISSUE TITLE
Add headers to Webpage data model

### ISSUE THREAD

**Issue by wdm0006** [anidata/rasp#8]
As mentioned in #5, it would be really useful to also get back the headers from a scraped webpage and keep them in the Webpage object for retrieval.  The Webpage object itself should be updated to include this, and all engines should support setting of headers in the returned objects.

**Comment by dlrobertson** [comment]
This would be awesome! and super easy for the Tor/Default engines. We should also report the status code (also very easy for the Tor/Default engines)

**Comment by hank-bond** [comment]
Looks like we can't implement this for `SeleniumEngine` due to the developers refusing to implement http headers and response codes.

[Look here](https://github.com/seleniumhq/selenium-google-code-issue-archive/issues/141), there are like 100+ comments between users professing their need for this feature and the developers repeatedly refusing.

**Comment by dlrobertson** [comment]
> Looks like we can't implement this for SeleniumEngine due to the developers refusing to implement http headers and response codes.

I'm fine with setting the value to `None` for the `SeleniumEngine`.

**Comment by wdm0006** [comment]
Yeah not a lot else to do there.
